version=1.1.2
group=top.mramericanmike.rmh
java_version=17

# Common
minecraft_version=1.20.1
mod_name=Remove Mouseover Highlight
mod_author=MrAmericanMike
mod_id=rmh
license=LGPL-3.0-only
credits=Remove Mouseover Highlight by MrAmericanMike
description=Remove Mouseover Highlight\nby MrAmericanMike
mod_logo_file=logo.png
mod_source_url=https://github.com/MrAmericanMike/RemoveMouseoverHighlight/
mod_issues_url=https://github.com/MrAmericanMike/RemoveMouseoverHighlight/issues
mod_display_url=https://www.curseforge.com/minecraft/mc-mods/remove-mouseover-highlight
minecraft_version_range=[1.20.1, 1.21)
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Fabric
fabric_version=0.92.1+1.20.1
fabric_loader_version=0.16.9

# Forge
forge_version=47.2.30
forge_loader_version_range=[47,)
forge_version_range=[47,)

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
