version=1.1.1
group=top.mramericanmike.rmh
java_version=21

# Common
minecraft_version=1.21.4
mod_name=Remove Mouseover Highlight
mod_author=MrAmericanMike
mod_id=rmh
license=LGPL-3.0-only
credits=Remove Mouseover Highlight by MrAmericanMike
description=Remove Mouseover Highlight\nby MrAmericanMike
mod_logo_file=logo.png
mod_source_url=https://github.com/MrAmericanMike/RemoveMouseoverHighlight/
mod_issues_url=https://github.com/MrAmericanMike/RemoveMouseoverHighlight/issues
mod_display_url=https://www.curseforge.com/minecraft/mc-mods/remove-mouseover-highlight
minecraft_version_range=[1.21.4, 1.22)
neo_form_version=1.21.4-20241203.161809
parchment_minecraft=1.21.4
parchment_version=2024.12.22

# Fabric
fabric_version=0.114.3+1.21.4
fabric_loader_version=0.16.10

# Forge
forge_version=54.0.17
forge_loader_version_range=[54,)

# NeoForge
neoforge_version=21.4.64-beta
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
