modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/MrAmericanMike/RemoveMouseoverHighlight/issues"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/remove-mouseover-highlight"
logoFile = "logo.png"
credits = "Remove Mouseover Highlight by MrAmericanMike"
authors = "${mod_authors}"
description = '''
Remove Mouseover Highlight
by MrAmericanMike
'''
[[dependencies.rmh]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "CLIENT"
[[dependencies.rmh]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
